// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cenco_pim

import (
	"cenco-pim/adapter/dependecy"
	"cenco-pim/app/handler"
	"cenco-pim/app/repository"
	"cenco-pim/app/router"
	"cenco-pim/app/service"
	"cenco-pim/util/logger"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeServer(dbConn *gorm.DB, logger2 *logger.Logger) dependecy.InitDependencyImpl {
	familyRepository := repository.NewFamilyRepository(dbConn, logger2)
	familyService := service.NewFamilyServiceImpl(familyRepository)
	familyHandler := handler.NewFamilyHandlerImpl(familyService)
	family := router.NewFamily(familyHandler, logger2)
	initDependencyImpl := dependecy.NewInitDependencyImpl(family)
	return initDependencyImpl
}
